CREATE TABLE `worldDataProto`.`magWeb` (
/* meta data */
	`sequenceNumber` SMALLINT UNSIGNED NOT NULL,
	`firmware_date` DATE NOT NULL,
/* packet ages determine what we want to insert and what we want to leave null */
	`age_inverter` TINYINT UNSIGNED NULL,
	`age_remote` TINYINT UNSIGNED NULL,
	`age_remote_0xA0` TINYINT UNSIGNED NULL,
	`age_remote_0xA1` TINYINT UNSIGNED NULL,
	`age_remote_0xA2` TINYINT UNSIGNED NULL,
	`age_remote_0xA3` TINYINT UNSIGNED NULL,
	`age_remote_0xA4` TINYINT UNSIGNED NULL,
	`age_remote_0x80` TINYINT UNSIGNED NULL,
	`age_ags_0xA1` TINYINT UNSIGNED NULL,
	`age_ags_0xA2` TINYINT UNSIGNED NULL,
	`age_rtr` TINYINT UNSIGNED NULL,
	`age_bmk` TINYINT UNSIGNED NULL,
/* inverter parameters */
	`i_status` TINYINT UNSIGNED NULL,
	`i_fault` TINYINT UNSIGNED NULL,
	`i_dc_volts` DECIMAL(2,1) UNSIGNED NULL,
	`i_dc_amps` TINYINT UNSIGNED NULL,
	`i_ac_volts_out` TINYINT UNSIGNED NULL,
	`i_ac_volts_in` TINYINT UNSIGNED NULL,
	`i_led_invert` TINYINT UNSIGNED NULL,
	`i_led_charge` TINYINT UNSIGNED NULL,
	`i_temp_battery` TINYINT UNSIGNED NULL,
	`i_temp_transformer` TINYINT UNSIGNED NULL,
	`i_temp_fet` TINYINT UNSIGNED NULL,
	`i_amps_in` TINYINT UNSIGNED NULL,
	`i_amps_out` TINYINT UNSIGNED NULL,
	`i_ac_hz` DECIMAL(2,1) UNSIGNED NULL,
	`i_stack_mode` TINYINT UNSIGNED NULL,
	`i_revision` DECIMAL(2,1) UNSIGNED NULL,
	`i_model` TINYINT UNSIGNED NULL,
/* remote */
	`r_search_watts` TINYINT UNSIGNED NULL,
	`r_battery_size` SMALLINT NULL,
	`r_battery_type` TINYINT UNSIGNED NULL,
	`r_absorb_volts` DECIMAL(2,1) UNSIGNED NULL,
	`r_charger_amps` TINYINT UNSIGNED NULL,
	`r_input_amps` TINYINT UNSIGNED NULL,
	`r_revision` DECIMAL(2,1) UNSIGNED  NULL,
	`r_parallel_threshold` TINYINT UNSIGNED NULL,
	`r_force_charge` TINYINT UNSIGNED NULL,
	`r_auto_genstart` TINYINT UNSIGNED NULL,
	`r_low_batt_cut_out` DECIMAL(2,1) UNSIGNED NULL,
	`r_vac_cut_out` TINYINT UNSIGNED NULL,
	`r_float_volts` DECIMAL(2,1) UNSIGNED NULL,
	`r_eq_volts` DECIMAL(2,1) UNSIGNED NULL,
	`r_absorb_time` TIME NULL,
/* remote 0xA0 footer */
	`r_ags_gen_run_time` TIME NULL,
	`r_ags_start_tempF` TINYINT UNSIGNED NULL,
	`r_ags_start_vdc` DECIMAL(2,1) UNSIGNED NULL,
	`r_ags_quiet_time` TINYINT UNSIGNED NULL,
/* remote 0xA1 footer */
	`r_ags_start_time` TIME NULL,
	`r_ags_stop_time` TIME NULL,
	`r_ags_stop_vdc` DECIMAL(2,1) UNSIGNED NULL,
	`r_ags_start_delay` TIME NULL,
	`r_ags_stop_delay` TIME NULL,
	`r_ags_max_run_time` TIME NULL,
/* remote 0xA2 footer */
	`r_ags_start_soc` TINYINT UNSIGNED NULL,
	`r_ags_stop_soc` TINYINT UNSIGNED NULL,
	`r_ags_start_amps` TINYINT UNSIGNED NULL,
	`r_ags_start_amps_delay` TIME NULL,
	`r_ags_stop_amps` TINYINT UNSIGNED NULL,
	`r_ags_stop_amps_delay` TIME NULL,
/* remote 0xA3 footer */
	`r_ags_quiet_time_begin` TIME NULL,
	`r_ags_quiet_time_end` TIME NULL,
	`r_ags_exercise_days` TINYINT UNSIGNED NULL,
	`r_ags_exercise_start` TIME NULL,
	`r_ags_exercise_run_time` TIME NULL,
	`r_ags_top_off` TIME NULL,
/* remote 0xA4 footer */
	`r_ags_warm_up` TIME NULL,
	`r_ags_cool_down` TIME NULL,
/* remote 0x80 footer */
	`r_bmk_efficiency` TINYINT UNSIGNED NULL,
	`r_bmk_battery_size` SMALLINT UNSIGNED NULL,
/* AGS parameters */
	`a_status` TINYINT UNSIGNED NULL,
	`a_temperature` TINYINT UNSIGNED NULL,
	`a_gen_run_time` TIME NULL,
	`a_voltage` DECIMAL(2,1) UNSIGNED NULL,
	`a_days_since_last` TINYINT UNSIGNED NULL,
	`a_revision` DECIMAL(2,1) UNSIGNED NULL,
/* BMK parameters */
	`b_state_of_charge` TINYINT UNSIGNED NULL,
	`b_dc_volts` DECIMAL(2,2) UNSIGNED NULL,
	`b_dc_amps` DECIMAL(3,2) NULL,
	`b_dc_min_volts` DECIMAL(2,2) UNSIGNED NULL,
	`b_dc_max_volts` DECIMAL(2,2) UNSIGNED NULL,
	`b_amph_in_out` SMALLINT NULL,
	`b_amph_trip` DECIMAL(4,1) NULL,
	`b_fault` TINYINT UNSIGNED NULL,
	`b_revision` DECIMAL(2,1) UNSIGNED NULL,
/* RTR parameters */
	`rtr_revision` DECIMAL(2,1) UNSIGNED NULL
) ENGINE = MYISAM
