#!/bin/bash
java -DSERIAL_PORT_LIST=/dev/ttyS0 -cp .:bin:commons-cli-1.2.jar:commons-lang3-3.1.jar:commons-math3-3.3.jar:gson-2.3.jar:mysql-connector-java-5.1.7-bin.jar:commons-collections4-4.0.jar:jspComm.jar:Serialio.jar dataGS.DataGS -j 8080 -r /dev/ttyS0 -R 57600 -l 4010 -i 10000 -c www/channels_magWebPro.json
