#!/bin/bash
cd ~aprs/DataGS
java -cp .:bin:commons-cli-1.2.jar:commons-lang3-3.1.jar:commons-math3-3.3.jar:gson-2.3.jar:mysql-connector-java-5.1.7-bin.jar dataGS.DataGS -l $1 -u root -p roadtoad -j 8080 -i 10000