#!/bin/bash
cd ~jjeffers/WorldDataCollector
java -cp .:bin:commons-cli-1.2.jar:commons-lang3-3.1.jar:/usr/share/java/mysql-connector-java.jar worldData.WorldDataCollector -l $1 -u worldDataInsert -p speedUp -e -q
#java -cp .:bin:commons-cli-1.2.jar:/usr/share/java/mysql-connector-java.jar WorldDataCollector -l $1 -u worldDataInsert -p speedUp
