#!/bin/bash
cd /home/aprs/DataGS
/usr/lib/jvm/java-7-openjdk-amd64/bin/java -DSERIAL_PORT_LIST=/dev/ttyUSB1 -cp .:jars:bin:jars/commons-cli-1.2.jar:jars/commons-lang3-3.3.2.jar:jars/commons-math3-3.3.jar:jars/gson-2.3.jar:jars/mysql-connector-java-5.1.7-bin.jar:jars/commons-collections4-4.0.jar:jars/jspComm.jar:jars/Serialio.jar:jars/json-lib-2.4-jdk15.jar:jars/commons-io-2.4.jar:jars/commons-csv-1.0.jar dataGS.DataGS -j 8080 -l 4010 -i 10000 -c channelDescriptions/channels_ps2tap.json -r /dev/ttyUSB1 -R 57600 -a -w /tmp/logLocal
